logicalclocks/ndb-chef

.kitchen.yml
Vagrantfile
attributes/default.rb
providers/mysql_basic.rb
providers/mysql_ndb.rb
recipes/install.rb
recipes/mysqld.rb
run-vagrant.sh
templates/default/mgm-server-start.sh.erb
templates/default/mysql-client.sh.erb
test_src/box_centos-7.0
test_src/box_ubuntu-15.10

Upgrade to version 7.5 of NDB and 5.7 for MySQL Server.

Upgrade MySQL Cluster 7.5

---

recipes/mgmd.rb
recipes/mysqld.rb
recipes/ndbd.rb

Support for ssl

---

attributes/default.rb
files/default/db_backup_rotation.sh
metadata.rb
recipes/mgmd.rb
recipes/ndbd.rb
templates/default/config.ini.erb
templates/default/native_ndb_backup.sh.erb
templates/default/ndb_backup_cleaner.sh.erb

[HOPSWORKS-434]  NDB backup script
[HOPSWORKS-434]  Perform sanity checks on backup properties
[HOPSWORKS-434]  Create local backup dir on mgm node
[HOPSWORKS-434]  Fix source name
[HOPSWORKS-434]  NDB backup cleaner script
[HOPSWORKS-434]  Bug fixes
[HOPSWORKS-434]  Add DB rotation script

[HOPSWORKS-434]  NDB backup script

---

recipes/mgmd.rb
recipes/mysqld.rb

https://hopshadoop.atlassian.net/browse/HOPSWORKS-555

[HOPSWORKS-555] Upgrade Support

---

files/default/db_backup_rotation.sh
templates/default/backup-remove.sh.erb
templates/default/backup-restore.sh.erb
templates/default/cluster-init.sh.erb
templates/default/cluster-shutdown.sh.erb
templates/default/cluster-start-with-recovery.sh.erb
templates/default/enter-singleuser-mode.sh.erb
templates/default/flexAsync.sh.erb
templates/default/get-mysql-port.sh.erb
templates/default/get-mysql-socket.sh.erb
templates/default/kill-process.sh.erb
templates/default/mgm-client.sh.erb
templates/default/mgm-server-start.sh.erb
templates/default/mgm-server-stop.sh.erb
templates/default/mysql-client.sh.erb
templates/default/mysql-server-start.sh.erb
templates/default/mysql-server-stop.sh.erb
templates/default/native_ndb_backup.sh.erb
templates/default/ndb_backup_cleaner.sh.erb
templates/default/ndbd-init.sh.erb
templates/default/ndbd-start.sh.erb
templates/default/ndbd-stop.sh.erb

[HOPSWORKS-623]  Fix bug with mysql-client
https://hopshadoop.atlassian.net/browse/HOPSWORKS-623

[HOPSWORKS-623]  Sanitize bash scripts

---

Karamelfile
recipes/mysqld.rb
recipes/ndbd.rb
templates/default/mysqld.service.erb
templates/default/ndbmtd.service.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091

[HOPSWORKS-1091] Add systemd unit file deps

---

.gitignore
Karamelfile
attributes/default.rb
metadata.rb
recipes/mysqld.rb
templates/default/grants.sql.erb
templates/default/my-ndb.cnf.erb

[HOPSWORKS-1140] Online featurestore

---

templates/default/cluster-init.sh.erb
templates/default/cluster-start-with-recovery.sh.erb
templates/default/kill-process.sh.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1323

[HOPSWORKS-1323] Fix bugs in MySQL cluster management scripts

---

metadata.rb
recipes/mgmd.rb
recipes/mysqld.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331

[HOPSWORKS-1331] Consistent flag for system upgrades

---

attributes/default.rb
metadata.rb
recipes/mysqld.rb

add mysql/initialize flag to disable mysql initialization

[HOPSWORKS-1359] MySQL server reinitialized during update to 1.0.0

---

templates/default/mgm-server-start.sh.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1507

[HOPSWORKS-1507] Check only for UDP or TCP sockets

---

recipes/mysqld_tls.rb
templates/default/grants.sql.erb
templates/default/my-ndb.cnf.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1577

[HOPSWORKS-1577] Rescrict allowed connections for admin user

---

attributes/default.rb
providers/mysql_basic.rb
recipes/mysqld.rb
recipes/mysqld_tls.rb
resources/mysql_basic.rb
templates/default/create-disk-table.sh.erb
templates/default/drop-disk-table.sh.erb
templates/default/grants.sql.erb
templates/default/my-ndb.cnf.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1825

[HOPSWORKS-1825] Connect to local mysqld

---

attributes/default.rb
metadata.rb
recipes/install.rb
recipes/mysqld_tls.rb
templates/default/my-ndb.cnf.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657

[HOPSWORKS-1657] System users x.509 v2

---

attributes/default.rb
metadata.rb
templates/default/ndbmtd.service.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1671

[HOPSWORKS-1671] Make ndbmtd Systemctl timeout default higher, configurable

---

recipes/mgmd.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1623

[HOPSWORKS-1623] overwrite config.ini on installation

---

templates/default/mysqld.service.erb
templates/default/mysqld_exporter.service.erb
templates/default/ndb_mgmd.service.erb
templates/default/ndbmtd.service.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065

[HOPSWORKS-2065] Automatically restart failed systemd units

---

templates/default/mysqld.service.erb
templates/default/mysqld_exporter.service.erb
templates/default/ndb_mgmd.service.erb
templates/default/ndbmtd.service.erb

* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Wait before each restart
* [HOPSWORKS-2065] Adjust mysqld burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065

[HOPSWORKS-2065] Automatically restart failed systemd units (#58)

---

attributes/default.rb
files/default/dbt2_run_1.conf.multi
files/default/dbt2_run_1.conf.single
recipes/bench.rb
templates/default/autobench_dbt2.conf.erb
templates/default/autobench_sysbench.conf.erb
templates/default/my-ndb.cnf.erb
templates/default/ndbmtd.service.erb

[irondb] Initial benchmark directories
[irondb] Add configuration for sysbench
[irondb] Change directory name
[irondb] Template sysbench multi
[irondb] Initialize local_infile mysql configuration property
[irondb] Add configuration files for dbt2
[irondb] Change dbt2 data directory
[irondb] Rename

[irondb] Change to RoNDB

---

recipes/mgmd.rb
templates/default/consul/mgm-consul.hcl.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2423

[HOPSWORKS-2423] Register RonDB Management server with Consul

---

attributes/default.rb
metadata.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2437

[HOPSWORKS-2437] Fix RonDB versioning attributes

---

attributes/default.rb
metadata.rb
recipes/mgmd.rb
templates/default/config.ini.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2421

[HOPSWORKS-2421] Template NumCPUs when configuration type is set to automatic

---

Berksfile
recipes/mgmd.rb
recipes/mysqld.rb
recipes/ndbd.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2546

[HOPSWORKS-2546] Remove guard when adding service to kagent services file

---

attributes/default.rb
recipes/install.rb
recipes/mysqld.rb
recipes/ndbd.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578

[HOPSWORKS-2578] Create RonDB data directories under data dir

---

templates/default/native_ndb_backup.sh.erb

* Remove the logic that sends the backup off the cluster, that
can be managed by another process or script
* Add backup of schema and users

Improve backup script

---

recipes/mgmd.rb
recipes/mysqld.rb
recipes/ndbd.rb
recipes/purge.rb

Reverts logicalclocks/ndb-chef#90

Revert "[HOPSWORKS-2808] Fix user home (#89)"

---

attributes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2679

[HOPSWORKS-2679] Bumpup RonDB version

---

attributes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-3041

[HOPSWORKS-3041] Bump up RonDB version to 21.04.4

---

templates/default/ndbmtd.service.erb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-3060

[HOPSWORKS-3060] Increase process priority for ndbmtd

---

recipes/install.rb
templates/default/mysqld.service.erb
templates/default/ndbmtd.service.erb

Resolves https://hopsworks.atlassian.net/browse/HOPSWORKS-3304

[HOPSWORKS-3304] Set Real-Time priority for mysql user and processes

---

templates/default/mysql-server-start.sh.erb

https://hopsworks.atlassian.net/browse/HWORKS-172

[HWORKS-172] Do not overwrite mysql server log upon restart

---

templates/default/mgm-server-start.sh.erb
templates/default/ndbmtd.service.erb

https://hopsworks.atlassian.net/browse/HWORKS-208

[HWORKS-208] Fine grain regular expression when checking if mgmd is running

---

templates/default/mysql-server-start.sh.erb

https://hopsworks.atlassian.net/browse/HWORKS-172

[HWORKS-172] append - do not overwrite mysql server log upon restart

---

attributes/default.rb

Reverts logicalclocks/ndb-chef#114

Revert "HOPSFS-52: Bumped RonDB to 21.04.10"

---

Karamelfile
files/default/restore_backup.sh
recipes/install.rb
recipes/ndb_restore_data.rb
recipes/ndb_restore_meta.rb
recipes/restore_sql.rb

[CLOUD-365] Fixes
https://hopsworks.atlassian.net/browse/CLOUD-365
[CLOUD-365]: https://hopsworks.atlassian.net/browse/CLOUD-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLOUD-365] Restore backup

---

attributes/default.rb
files/default/restore_backup.sh
metadata.rb
recipes/ndb_restore_data.rb
recipes/ndb_restore_meta.rb
recipes/restore_sql.rb
templates/default/native_ndb_backup.sh.erb

https://hopsworks.atlassian.net/browse/CLOUD-365
Complementary to https://github.com/logicalclocks/ndb-chef/commit/0d1741d72a0a8cef8420b31b1eb4b4acc6a08878

[CLOUD-365] Restore RonDB backup as part of installation

---

recipes/restore_sql.rb

https://hopsworks.atlassian.net/browse/CLOUD-365

[CLOUD-365] Fix placement of drop statements

---

recipes/restore_sql.rb

https://hopsworks.atlassian.net/browse/CLOUD-365

[CLOUD-365] Fix variable declaration

---

attributes/default.rb
files/default/restore_backup.sh
metadata.rb
recipes/install.rb
recipes/ndb_restore_data.rb
recipes/ndb_restore_meta.rb
recipes/restore_sql.rb

[CLOUD-408] Append to restore log file
[CLOUD-408] Tarball validation
[CLOUD-408] Add option to restore multipart backup serially to mitigate bug in RonDB with limited resources
[CLOUD-408] Restore backup metadata only once
[CLOUD-408]: https://hopsworks.atlassian.net/browse/CLOUD-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-408]: https://hopsworks.atlassian.net/browse/CLOUD-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-408]: https://hopsworks.atlassian.net/browse/CLOUD-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-408]: https://hopsworks.atlassian.net/browse/CLOUD-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

[CLOUD-408] Add support to download RonDB backup tarball

---

attributes/default.rb

Reverts logicalclocks/ndb-chef#128

Revert "HOPSFS-67: Bumped RonDB version to 21.04.12"

---

libraries/default.rb
recipes/ndb_restore_data.rb
recipes/ndb_restore_meta.rb
recipes/restore_sql.rb

* [CLOUD-408] Fix restore backup guards
* [CLOUD-408] Move guards to function
[CLOUD-408]: https://hopsworks.atlassian.net/browse/CLOUD-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-408]: https://hopsworks.atlassian.net/browse/CLOUD-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLOUD-408] Fix restore backup guards (#126)

---

templates/default/mysql-server-start.sh.erb

Fixes https://hopsworks.atlassian.net/browse/CLOUD-514

[CLOUD-514] fix mysqld stuck in starting in systemctl

---

recipes/restore_sql.rb

https://hopsworks.atlassian.net/browse/HWORKS-643

[HWORKS-643] Revoke new Glassfish'es internal certificate during backup restoration

---

attributes/default.rb
files/default/restore_backup.sh
recipes/ndb_restore_data.rb
recipes/ndb_restore_meta.rb
recipes/restore_sql.rb

https://hopsworks.atlassian.net/browse/HWORKS-634
Revisit the process of restoring RonDB. In general the steps are the following
1. Restore metadata from ndb native backup with disabling indices
2. Restore data from ndb native backup
3. Rebuild indices
4. Restore views and stored procedures
5. Restore MySQL users
6. Execute SHOW TABLES for all databases

[HWORKS-634] Revisit RonDB restore process

---

attributes/default.rb
metadata.rb
templates/default/my-ndb.cnf.erb

https://hopsworks.atlassian.net/browse/HWORKS-667

[HWORKS-667] Change default location of X plugin socket

---

attributes/default.rb
metadata.rb
recipes/rdrs.rb

https://hopsworks.atlassian.net/browse/HWORKS-678

[HWORKS-678] Expose attributes to configure RDRS to use user issued certificate

---

Karamelfile

https://hopsworks.atlassian.net/browse/HWORKS-702
Only setting recipe dependencies for Karamel

[HWORKS-702] Setup global replication recipe dependencies

---

Karamelfile
attributes/default.rb
files/default/restore_backup.sh
libraries/default.rb
metadata.rb
recipes/backup.rb
recipes/download_backup.rb
recipes/mysql_primary.rb
recipes/mysql_replica.rb
recipes/mysqld.rb
recipes/mysqld_tls.rb
recipes/ndb_restore_data.rb
recipes/ndb_restore_meta.rb
recipes/replication_common.rb
recipes/replication_configuration.rb
recipes/restore_sql.rb
templates/default/my-ndb.cnf.erb
templates/default/native_ndb_backup.sh.erb
templates/default/replication/heartbeat_tbl.sql.erb
templates/default/replication/heartbeater.sh.erb
templates/default/replication/replication_conf.sql.erb
templates/default/replication/replication_configuration.sh.erb
templates/default/replication/replication_monitor.sh.erb
templates/default/replication/rondb-heartbeater.service.erb
templates/default/replication/rondb-monitor.service.erb

https://hopsworks.atlassian.net/browse/HWORKS-702

[HWORKS-702] Configuration and monitoring for RonDB Global replication

---

files/default/restore_backup.sh

https://hopsworks.atlassian.net/browse/CLOUD-650

[CLOUD-650] Add option to skip restoring disk data objects

---

templates/default/replication/heartbeater.sh.erb
templates/default/replication/replication_configuration.sh.erb
templates/default/replication/replication_monitor.sh.erb

https://hopsworks.atlassian.net/browse/HWORKS-817

[HWORKS-817] Fix log level evaluation

---

files/default/restore_backup.sh
templates/default/native_ndb_backup.sh.erb

https://hopsworks.atlassian.net/browse/HWORKS-837

[HWORKS-837] Do not mysqldump if there are no databases to backup, we need to backup anything else though such as users

---

attributes/default.rb
metadata.rb
recipes/mgmd.rb

RONDB-519: Bump RonDB version to 22.10.1

RONDB-519: Bump RonDB version to 22.10.1

---

files/default/restore_backup.sh

https://hopsworks.atlassian.net/browse/HWORKS-890

[HWORKS-890] Allow restore-data to restore data even on tables with indexes

---

files/default/restore_backup.sh

This reverts commit 8333b23b007db8a63ca4c599f7280332aa7687ad.

[revert_HWORKS-890_3.5] Revert "[HWORKS-890] Allow restore-data to restore data even on tables with indexes

---

attributes/default.rb
metadata.rb
templates/default/my-ndb.cnf.erb

https://hopsworks.atlassian.net/browse/HWORKS-961

[HWORKS-961] Turn on binlog only when replication is enabled

---

recipes/install.rb

Fixes https://hopsworks.atlassian.net/browse/HWORKS-955

[HWORKS-955] Install libnuma1 on debian

---

recipes/install.rb

https://hopsworks.atlassian.net/browse/HWORKS-974

[HWORKS-974] Change file to guard for

---

files/default/restore_backup.sh

https://hopsworks.atlassian.net/browse/HWORKS-976

[HWORKS-976] Fix replacement of CREATE USER statement

---

recipes/mysqld.rb
recipes/ndbd.rb
recipes/rdrs.rb
templates/default/ndb_mgmd.service.erb

https://hopsworks.atlassian.net/browse/HWORKS-946

[HWORKS-946] Extra After systemd units

---

attributes/default.rb
metadata.rb
recipes/mysql_primary.rb
recipes/mysql_replica.rb
templates/default/my-ndb.cnf.erb
templates/default/replication/replication_grants.sql.erb
templates/default/replication/replication_monitor.sh.erb

https://hopsworks.atlassian.net/browse/HWORKS-962

[HWORKS-962] Mechanism to purge applied binary logs in Primary MySQL servers

---

attributes/default.rb

https://hopsworks.atlassian.net/browse/HWORKS-1097

[HWORKS-1097] Bump RonDB version to address critical bug in ndbmtd

---

templates/default/my-ndb.cnf.erb

https://hopsworks.atlassian.net/browse/HWORKS-1143

[HWORKS-1143] Remove ndb_apply_status from the list of excluded replication tables

---

attributes/default.rb
libraries/default.rb
metadata.rb
recipes/commit_upgrade.rb
recipes/mysqld.rb
recipes/mysqld_tls.rb
templates/default/my-ndb.cnf.erb

https://hopsworks.atlassian.net/browse/HWORKS-1057

[HWORKS-1057] MySQL safe upgrade and recipe to commit upgrade

---

recipes/mysqld.rb

https://hopsworks.atlassian.net/browse/HWORKS-1177

[HWORKS-1177] Template replication scripts in mysqld recipe for upgrades

---

attributes/default.rb
metadata.rb
recipes/restore_sql.rb

https://hopsworks.atlassian.net/browse/HWORKS-1179

[HWORKS-1179] Avoid deleting Hopsworks certificates when restoring a database backup unless if it's a disaster recovery

---

attributes/default.rb

RONDB-661 RonDB minor release 22.10.3

RONDB-661 RonDB minor release 22.10.3
